[project]
name = "documentation-helper"
version = "0.1.0"
description = "Documentation helper with AI capabilities"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4",
    "black",
    "tiktoken",
    "openai",
    "unstructured",
    "nltk",
    "fastapi",
    "jinja2",
    "uvicorn",
    "streamlit",
    "streamlit-chat",
    "tqdm",
    "isort",
    "langchainhub",
    "firecrawl-py",
    "langchain-community",
    "langsmith",
    "pillow",
    "langchain-tavily",
    "langchain-pinecone",
    "certifi",
    "langchain-chroma",
    "python-dotenv",
    "langchain-text-splitters>=1.1.2",
    "protobuf<=3.20.3",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
]
